"use client";

import * as React from "react";
import {
  EventCalendarDemo,
  GanttChartDemo,
  GanttChartPlanningDemo,
  KanbanDemo,
  SplitViewDemo,
  SplitViewWorkspaceDemo,
  TableDemo,
  TableEmptyDemo,
  TablePaginationDemo,
  TableWorkbenchDemo,
  WorkflowCanvasDemo,
  WorkflowCanvasNestedDemo,
  WorkflowCanvasPaletteDemo,
} from "./demos/composites";
import {
  ChatComposerDemo,
  ConversationRailDemo,
  ChatComposerFullDemo,
  ChatComposerInlineDemo,
  ComposerQueueDemo,
  MessageDemo,
  MessageScrollerDemo,
  MessageRichStreamDemo,
  MessageStreamDemo,
  ToolApprovalDemo,
  ToolApprovalFlowDemo,
  ToolApprovalMobileDemo,
  ToolApprovalNotchDemo,
  ToolCallDemo,
  ToolCallStatesDemo,
  ModelPickerDemo,
  SelectionTooltipDemo,
  SelectionTooltipShelfDemo,
} from "./demos/agent";
import {
  AgentActivityCardDemo,
  AgentActivityDemo,
  AgentDetailsDemo,
  ConversationHistoryDemo,
  TranscriptDividerDemo,
  TranscriptDividerDetailDemo,
} from "./demos/agent";
import {
  AppShellDemo,
  ContextMenuDemo,
  PopoverSurfaceDemo,
  PopoverSurfaceVariantsDemo,
  SearchableListboxDemo,
  SectionedListboxDemo,
  SidebarDemo,
} from "./demos/shell";
import {
  ChatComposerEditorDemo,
  ComposerAccessModeDemo,
  GeneratingSurfaceDemo,
  ModelCapabilityControlsDemo,
  ModelThinkingSliderDemo,
  QuestionnaireDemo,
  QuestionnaireMixedDemo,
} from "./demos/conversation";
import {
  FlowChartDemo,
  FlowChartVerticalDemo,
  PieChartDemo,
  PieChartDonutDemo,
  PieChartGaugeDemo,
  PriceChartCandlesDemo,
  PriceChartDemo,
  PriceChartSparklineDemo,
  RadarChartDemo,
  RadarChartPerAxisDemo,
  StockQuoteDemo,
} from "./demos/charts";
import {
  ChatAnnotationsDemo,
  ChatAnnotationsSentDemo,
  ChatBubblesDemo,
  ChatBubblesTypingDemo,
  ChatOverlayDemo,
  ChatTabsDemo,
  ChatTrayCollapseDemo,
  ChatTrayDemo,
  PillComposerDemo,
} from "./demos/chat";
import {
  DrawerDemo,
  DrawerResizableDemo,
  FileDropZoneDemo,
  FileDropZoneLimitsDemo,
  FilePreviewDemo,
  FilePreviewFallbackDemo,
  GradientSurfaceDemo,
  GradientSurfacePalettesDemo,
  GradientSurfacePatternsDemo,
  PageOutlineCollapseDemo,
  PageOutlineDemo,
  PageOutlineMarkerDemo,
  SheetContainedDemo,
  SheetDemo,
  TabsDemo,
  TabsPillDemo,
  TaskListChecklistDemo,
  TaskListDemo,
} from "./demos/surfaces";
import { AgentHarness } from "./demos/harness";
import {
  BadgeDemo,
  ButtonDemo,
  CardDemo,
  CheckboxDemo,
  CheckboxStatesDemo,
  CodeBlockDemo,
  DropdownMenuDemo,
  FileDiffDemo,
  FileDiffScrollDemo,
  MermaidDiagramDemo,
  InputDemo,
  JsonTreeDemo,
  MathBlockDemo,
  MessageMarkdownDemo,
  PaginationDemo,
  RandomAvatarDemo,
  RandomAvatarGroupDemo,
  RandomAvatarToneDemo,
  RandomAvatarWorkingDemo,
  ReferenceDemo,
  SegmentedControlDemo,
  TimelineHeaderDemo,
} from "./demos/content";

/**
 * Live previews, keyed by component slug and by example id. Every one renders
 * the real @nessa-ui/react component — the docs never re-implement anything.
 */
export const previews: Record<string, React.ReactNode> = {
  // primitives
  button: <ButtonDemo />,
  badge: <BadgeDemo />,
  card: <CardDemo />,
  input: <InputDemo />,
  "segmented-control": <SegmentedControlDemo />,
  "random-avatar": <RandomAvatarDemo />,
  "random-avatar-group": <RandomAvatarGroupDemo />,
  "random-avatar-working": <RandomAvatarWorkingDemo />,
  "random-avatar-tones": <RandomAvatarToneDemo />,
  checkbox: <CheckboxDemo />,
  "checkbox-states": <CheckboxStatesDemo />,
  "dropdown-menu": <DropdownMenuDemo />,
  "context-menu": <ContextMenuDemo />,
  "popover-surface": <PopoverSurfaceDemo />,
  "popover-surface-variants": <PopoverSurfaceVariantsDemo />,
  "searchable-listbox": <SearchableListboxDemo />,
  "sectioned-listbox": <SectionedListboxDemo />,
  pagination: <PaginationDemo />,
  "timeline-header": <TimelineHeaderDemo />,
  tabs: <TabsDemo />,
  "tabs-pill": <TabsPillDemo />,
  "task-list": <TaskListDemo />,
  "task-list-checklist": <TaskListChecklistDemo />,
  "gradient-surface": <GradientSurfaceDemo />,
  "gradient-surface-palettes": <GradientSurfacePalettesDemo />,
  "gradient-surface-patterns": <GradientSurfacePatternsDemo />,
  drawer: <DrawerDemo />,
  "drawer-resizable": <DrawerResizableDemo />,
  sheet: <SheetDemo />,
  "sheet-contained": <SheetContainedDemo />,

  // content
  "code-block": <CodeBlockDemo />,
  "json-tree": <JsonTreeDemo />,
  "json-tree-collapsible": <JsonTreeDemo collapsible />,
  "math-block": <MathBlockDemo />,
  "message-markdown": <MessageMarkdownDemo />,
  reference: <ReferenceDemo />,
  "file-diff-list": <FileDiffDemo />,
  "file-diff-scroll": <FileDiffScrollDemo />,
  "mermaid-diagram": <MermaidDiagramDemo />,
  "page-outline": <PageOutlineDemo />,
  "page-outline-collapse": <PageOutlineCollapseDemo />,
  "page-outline-marker": <PageOutlineMarkerDemo />,
  "file-preview": <FilePreviewDemo />,
  "file-preview-fallback": <FilePreviewFallbackDemo />,
  "file-drop-zone": <FileDropZoneDemo />,
  "file-drop-zone-limits": <FileDropZoneLimitsDemo />,

  // charts
  "pie-chart": <PieChartDemo />,
  "pie-chart-donut": <PieChartDonutDemo />,
  "pie-chart-gauge": <PieChartGaugeDemo />,
  "radar-chart": <RadarChartDemo />,
  "radar-chart-per-axis": <RadarChartPerAxisDemo />,
  "flow-chart": <FlowChartDemo />,
  "flow-chart-vertical": <FlowChartVerticalDemo />,
  "price-chart": <PriceChartDemo />,
  "price-chart-candles": <PriceChartCandlesDemo />,
  "price-chart-sparklines": <PriceChartSparklineDemo />,
  "stock-quote": <StockQuoteDemo />,

  // agent surfaces
  "conversation-rail": <ConversationRailDemo />,
  "message-scroller": <MessageScrollerDemo />,
  message: <MessageDemo />,
  "message-streaming": <MessageStreamDemo />,
  "message-rich-streaming": <MessageRichStreamDemo />,
  "tool-call": <ToolCallDemo />,
  "tool-call-states": <ToolCallStatesDemo />,
  "tool-approval": <ToolApprovalDemo />,
  "tool-approval-flow": <ToolApprovalFlowDemo />,
  "tool-approval-notch": <ToolApprovalNotchDemo />,
  "tool-approval-mobile": <ToolApprovalMobileDemo />,
  "chat-composer": <ChatComposerDemo />,
  "chat-composer-full": <ChatComposerFullDemo />,
  "chat-composer-inline": <ChatComposerInlineDemo />,
  "composer-queue": <ComposerQueueDemo />,
  "model-picker": <ModelPickerDemo />,
  "selection-tooltip": <SelectionTooltipDemo />,
  "selection-tooltip-shelf": <SelectionTooltipShelfDemo />,
  "agent-activity": <AgentActivityDemo />,
  "agent-activity-card": <AgentActivityCardDemo />,
  "agent-details": <AgentDetailsDemo />,
  "conversation-history": <ConversationHistoryDemo />,
  "chat-composer-editor": <ChatComposerEditorDemo />,
  "composer-access-mode": <ComposerAccessModeDemo />,
  "model-capability-controls": <ModelCapabilityControlsDemo />,
  "model-thinking-slider": <ModelThinkingSliderDemo />,
  "generating-surface": <GeneratingSurfaceDemo />,
  questionnaire: <QuestionnaireDemo />,
  "questionnaire-mixed": <QuestionnaireMixedDemo />,
  "transcript-divider": <TranscriptDividerDemo />,
  "transcript-divider-detail": <TranscriptDividerDetailDemo />,

  // chat surfaces
  "pill-composer": <PillComposerDemo />,
  "chat-bubbles": <ChatBubblesDemo />,
  "chat-bubbles-typing": <ChatBubblesTypingDemo />,
  "chat-tabs": <ChatTabsDemo />,
  "chat-tray": <ChatTrayDemo />,
  "chat-tray-collapse": <ChatTrayCollapseDemo />,
  "chat-overlay": <ChatOverlayDemo />,
  "chat-annotations": <ChatAnnotationsDemo />,
  "chat-annotations-sent": <ChatAnnotationsSentDemo />,

  // harness
  "agent-harness": <AgentHarness />,

  // composites
  "event-calendar": <EventCalendarDemo />,
  "gantt-chart": <GanttChartDemo />,
  "gantt-chart-planning": <GanttChartPlanningDemo />,
  kanban: <KanbanDemo />,
  sidebar: <SidebarDemo />,
  "app-shell": <AppShellDemo />,
  "split-view": <SplitViewDemo />,
  "split-view-workspace": <SplitViewWorkspaceDemo />,
  "workflow-canvas": <WorkflowCanvasDemo />,
  "workflow-canvas-nested": <WorkflowCanvasNestedDemo />,
  "workflow-canvas-palette": <WorkflowCanvasPaletteDemo />,
  table: <TableDemo />,
  "table-workbench": <TableWorkbenchDemo />,
  "table-pagination": <TablePaginationDemo />,
  "table-empty": <TableEmptyDemo />,
};
